Use factories for SSH and Shells to make them configurable/testable
district09/symfony_bundle_domainator9k-core pull request #1
Opened 2017-11-08 08:15 UTC by Jelle-S

2017-11-08 13:47 UTC, daften requested changes

2017-11-08 13:47 UTC, daften commented on Ssh/Factory/SshShellFactory.php
> +    public function create($host, $authType, $user, $password = null)
docblock? inheritdoc tag?

2017-11-08 13:47 UTC, daften commented on Task/AbstractTask.php
> +use DigipolisGent\Domainator9k\CoreBundle\Ssh\Factory\SshShellFactoryInterface;
Doesn't this, and everything related, belong in AbstractSshTask?

2017-11-08 13:47 UTC, daften commented on Task/Provision/ConfigFiles.php
> +class ConfigFiles extends AbstractTask implements TaskFactoryAwareInterface
Maybe adapt the class name to have Task suffix? General guideline for tasks?

2017-11-08 13:47 UTC, daften commented on Task/TaskInterface.php
> +    public function setShellFactory(SshShellFactoryInterface $sshShellFactory);
Also here, there seems to be a mix between task and sshtask.

2017-11-13 09:44 UTC, daften requested changes
In general (nitpicking): no docblocks for classes / interfaces.

2017-11-13 09:44 UTC, daften commented on Ssh/SshShell.php
> +// @codeCoverageIgnoreStart
Inconsistency, here no empty line after the comment, at the codeCoverageIgnoreEnd comment there is a line before.

2017-11-13 09:44 UTC, daften commented on Task/Factory.php
> +     * @return AbstractSshTask
Doesn't seem right, since you check for is_subclass_of($class, SshTaskInterface::class) below, shouldn't this remain AbstractTask type?

2017-11-13 09:44 UTC, daften commented on Ssh/SshShell.php
> +    protected function assertConnection($auth = true)
Nitpicking: Double use of $auth (as property and as argument here), maybe rename this one?

2017-11-13 16:56 UTC, daften approved these changes

2017-11-13 16:57 UTC, daften commented
@Jelle-S Travis fails though

2017-11-13 22:15 UTC, dubgeiser reviewed
- Good to see static stuff go. \o/
  - Although class names are quite clear, some form of doc comments on classes and interfaces would be welcome (and probably shut up some coding standards checkers).
  - Travis fails?

2017-11-13 22:15 UTC, dubgeiser commented on Ssh/SshShellInterface.php
> +     *     Will be filled with the command exit status or null of unknown.
'null if unknow.'

2017-11-13 22:15 UTC, dubgeiser commented on Tests/Task/Filesystem/CreateFileTaskTest.php
> + * Description of CreateFileTaskTest
IDE-generated comment, I presume ;-)

2017-11-14 09:23 UTC, merged